version: '3'
services:
  app:
    image: index.docker.io/jmtimper/dynasty-daddy-front-end:latest
    ports:
      - "4200:4200"
    container_name: dynasty-daddy-app
    restart: always
    depends_on:
      - api
      - db
    links:
      - api
  api:
    image: index.docker.io/jmtimper/dynasty-daddy-back-end:latest
    env_file:
      - .env.api
    ports:
      - "3000:3000"
    container_name: dynasty-daddy-api
    restart: always
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
    restart: unless-stopped
    env_file:
      - .env.db
    volumes:
      - ./sql/01_create_tables.sql:/docker-entrypoint-initdb.d/01_create_tables.sql
      - ./sql/02_fill_player_ids.sql:/docker-entrypoint-initdb.d/02_fill_player_ids.sql
      - ./sql/03_fill_player_info.sql:/docker-entrypoint-initdb.d/03_fill_player_info.sql
      - ./sql/04_fill_player_values.sql:/docker-entrypoint-initdb.d/04_fill_player_values.sql
      - ./db_v0.1.2/pgsql:/var/lib/postgresql/data
  scraper:
    image: index.docker.io/jmtimper/dynasty-daddy-cron:latest
    env_file: .env.cron
    container_name: dynasty-daddy-cron
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30
